#pragma kernel CSParticle
#pragma kernel CSClear

struct particle
{
    float2 pos;
    float2 vel;
};
RWStructuredBuffer<particle> particlesBuffer;
uint particleCount;

float dt;
float2 mousePos;
float2 screenSize;

RWTexture2D<float> densityMap;
float2 res;
float thickness;

//fluid sim vars
float pressureRadius;
float mass;
float targetDensity;
float pressureMultiplier;
float damping;
float viscosityStrength;

float gravity;
float elasticity;

float2 bounds;

[numthreads(8, 8, 1)]
void CSClear(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint) res.x || id.y >= (uint) res.y)
        return;
    densityMap[id.xy] = 0;
}

[numthreads(256, 1, 1)]
void CSParticle(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= particleCount) return;
    particle current = particlesBuffer[id.x];
    
    current.pos += current.vel * dt;
    
    uint2 pixelPos = clamp((uint2) (((current.pos + screenSize) / (2.0 * screenSize)) * res), uint2(0, 0), uint2(res) - 1);
    densityMap[pixelPos.xy] = clamp(densityMap[pixelPos.xy] + thickness, 0, 1);
    particlesBuffer[id.x] = current;
}
